language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"
  - "3.7"

notifications:
  email: true

before_install:
  # override the default environment to test against conda, see:
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION jupyter nltk
  - conda activate test-environment

install:
  # test kernel installation
  - ./install_lambda_kernel.py
  - jupyter kernelspec list

script:
  # test that kernel got installed
  - echo 'te("x_e"); exit()' | jupyter run --kernel=lambda-notebook
  # run the unit tests
  - make unittest
  # execute notebooks in the repository
  - make testnb
